/**
 * tools/build.mjs — derived artifacts owned by maintained libraries (Node side).
 *
 * Migrated off tools/build.py's string surgery:
 *   sitemap.xml                  -> xmlbuilder2 (XML escaping in a library)
 *   lighthouserc(.mobile).json   -> URLs derived from the generated sitemap, so
 *                                   there is one page list instead of three
 *   sw.js                        -> workbox-build generateSW
 *   assets/js/i18n.js            -> generated from assets/locales/{en,zh}.json
 *
 * Page markup (nav/footer partials, tutorial/fraud bodies, head meta, fallback
 * text) stays in tools/build.py: cheerio proved able to do it but re-serializes
 * every document (~7,300 lines of churn per full run, e.g. `<circle/>` becomes
 * `<circle></circle>`), which is a bad trade for a hand-audited static site.
 *
 * Usage: node tools/build.mjs [build|check]      (check exits 1 on drift)
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { create } from 'xmlbuilder2';
import { generateSW } from 'workbox-build';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE_BASE = 'https://lxh113377.github.io/filialconnect';
const LHCI_BASE = 'http://127.0.0.1:8765/filialconnect';
const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const write = (p, text) => writeFileSync(join(ROOT, p), text, 'utf8');

export const allPages = () => ['index.html', '404.html']
  .concat(readdirSync(join(ROOT, 'pages')).filter((f) => f.endsWith('.html')).sort().map((f) => 'pages/' + f));

export const canonicalFor = (fp) =>
  SITE_BASE + (fp === 'index.html' ? '/' : '/' + fp);

export function buildSitemap() {
  const root = create({ version: '1.0', encoding: 'UTF-8' })
    .ele('urlset', { xmlns: 'http://www.sitemaps.org/schemas/sitemap/0.9' });
  for (const fp of allPages()) {
    if (fp === '404.html') continue;
    root.ele('url').ele('loc').txt(canonicalFor(fp)).up().up();
  }
  // xmlbuilder2 builds and escapes the XML; these two lines only restore the
  // house layout (declaration on its own line, two-space indent per <url>).
  return root.end({ prettyPrint: false })
    .replace(/^<\?xml([^?]*)\?>/, '<?xml$1?>\n')
    .replace(/><url>/, '>\n  <url>')
    .replace(/<\/url><url>/g, '</url>\n  <url>')
    .replace(/<\/urlset>$/, '\n</urlset>\n');
}

const lhUrls = (pages) => pages.map((fp) => (fp === 'index.html' ? `${LHCI_BASE}/` : `${LHCI_BASE}/${fp}`));

const DESKTOP_ASSERT = {
  'categories:performance': ['error', { minScore: 0.9 }],
  'categories:accessibility': ['error', { minScore: 0.95 }],
  'categories:best-practices': ['warn', { minScore: 0.9 }],
  'categories:seo': ['warn', { minScore: 0.9 }],
};
const MOBILE_PRIORITY = ['index.html', 'pages/tutorials.html', 'pages/fraud-database.html', 'pages/call-help.html'];

/** Page list comes from sitemap.xml, the one place that now declares it. */
export function pagesFromSitemap() {
  return [...read('sitemap.xml').matchAll(/<loc>([^<]+)<\/loc>/g)]
    .map((m) => m[1].replace(SITE_BASE + '/', '').replace(/^$/, 'index.html'))
    .map((p) => (p === SITE_BASE + '/' || p === '' ? 'index.html' : p));
}

export function buildLighthouserc() {
  const pages = pagesFromSitemap();
  const order = ['index.html', '404.html'].concat(pages.filter((p) => p !== 'index.html' && p !== '404.html'));
  const cfg = {
    ci: {
      collect: { url: lhUrls(order), numberOfRuns: 2, settings: { preset: 'desktop' } },
      assert: { assertions: DESKTOP_ASSERT },
    },
  };
  return JSON.stringify(cfg, null, 2) + '\n';
}

export function buildLighthousercMobile() {
  const cfg = {
    ci: {
      collect: {
        url: lhUrls(MOBILE_PRIORITY),
        numberOfRuns: 3,
        settings: {
          formFactor: 'mobile',
          screenEmulation: { width: 412, height: 846, deviceScaleFactor: 1.75, mobile: true },
          throttlingMethod: 'simulate',
        },
      },
      assert: { assertions: { ...DESKTOP_ASSERT, 'categories:performance': ['error', { minScore: 0.85 }] } },
    },
  };
  return JSON.stringify(cfg, null, 2) + '\n';
}

export function buildI18nJs() {
  const en = JSON.parse(read('assets/locales/en.json'));
  const zh = JSON.parse(read('assets/locales/zh.json'));
  const block = (name, dict) => `  ${name}: {\n`
    + Object.keys(dict).map((k) => `    ${JSON.stringify(k)}: ${JSON.stringify(dict[k])},`).join('\n')
    + '\n  },';
  return '/**\n * FilialConnect (XiaoXinLian) — i18n dictionary.\n'
    + ' * GENERATED by tools/build.mjs from assets/locales/{en,zh}.json — edit the JSON, not this file.\n'
    + ' * Consumed by i18next (see assets/js/main.js).\n */\nvar I18N = {\n'
    + block('en', en) + '\n' + block('zh', zh).replace(/,$/, '') + '\n};\n';
}

const SW_SOURCES = ['**/*.html', 'manifest.json'];

/** Copy the runtime i18n libraries into the site so nothing is fetched remotely. */
export function copyVendor() {
  const files = [
    ['i18next/dist/umd/i18next.min.js', 'assets/vendor/i18next.min.js'],
    ['i18next-browser-languagedetector/dist/umd/i18nextBrowserLanguageDetector.min.js',
      'assets/vendor/i18next-browser-languagedetector.min.js'],
  ];
  const out = [];
  for (const [src, dst] of files) {
    const text = readFileSync(join(ROOT, 'node_modules', src), 'utf8');
    if (!existsSync(join(ROOT, dirname(dst)))) mkdirSync(join(ROOT, dirname(dst)), { recursive: true });
    if (!existsSync(join(ROOT, dst)) || readFileSync(join(ROOT, dst), 'utf8') !== text) {
      writeFileSync(join(ROOT, dst), text, 'utf8');
      out.push(dst);
    }
  }
  return out;
}

export async function buildSw(dest = ROOT) {
  const { count, warnings } = await generateSW({
    swDest: join(dest, 'sw.js'),
    globDirectory: ROOT,
    globPatterns: SW_SOURCES,
    cacheId: 'filialconnect-v1',
    skipWaiting: true,
    clientsClaim: true,
    cleanupOutdatedCaches: true,
    sourcemap: false,
    // Honest freshness rules: a stale scam list or page must never beat the network.
    runtimeCaching: [
      { urlPattern: ({ sameOrigin, request }) => sameOrigin
          && (request.destination === 'document' || request.url.includes('/assets/data/')),
        handler: 'NetworkFirst', options: { cacheName: 'fc-network-first', networkTimeoutSeconds: 4 } },
      { urlPattern: ({ sameOrigin, request }) => sameOrigin
          && /\/assets\/images\/.*\.(png|jpg|jpeg|webp|svg)$/.test(request.url),
        handler: 'CacheFirst', options: { cacheName: 'fc-images' } },
      { urlPattern: ({ sameOrigin, request }) => sameOrigin && request.url.endsWith('/manifest.json'),
        handler: 'CacheFirst', options: { cacheName: 'fc-manifest' } },
    ],
  });
  if (warnings && warnings.length) console.log('workbox warnings:', warnings.join('; '));
  return count;
}

function artifacts() {
  return {
    'sitemap.xml': buildSitemap(),
    'lighthouserc.json': buildLighthouserc(),
    'lighthouserc.mobile.json': buildLighthousercMobile(),
    'assets/js/i18n.js': buildI18nJs(),
  };
}

/** Regenerate the service worker into a temp dir and compare, so a gutted or
 *  stale sw.js cannot pass the gate silently (workbox output is deterministic). */
export async function checkSw() {
  const tmp = mkdtempSync(join(tmpdir(), 'fc-sw-'));
  try {
    await buildSw(tmp);
    const gen = readFileSync(join(tmp, 'sw.js'), 'utf8');
    const committed = readFileSync(join(ROOT, 'sw.js'), 'utf8');
    if (gen !== committed) return 'sw.js differs from workbox output (run: node tools/build.mjs)';
    const missing = allPages().filter((p) => !committed.includes(p.replace(/'/g, '')));
    if (missing.length) return `sw.js precache is missing: ${missing.join(', ')}`;
    return null;
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

async function main() {
  const mode = process.argv[2] || 'build';
  const want = artifacts();
  if (mode === 'check') {
    const drift = Object.entries(want).filter(([p, text]) => read(p) !== text).map(([p]) => p);
    const swProblem = await checkSw();
    if (swProblem) drift.push(swProblem);
    if (drift.length) {
      console.log('FAIL: node-owned artifacts drift (run: node tools/build.mjs):');
      drift.forEach((d) => console.log('  ' + d));
      process.exit(1);
    }
    console.log(`check: ${Object.keys(want).length} node-owned artifacts in sync (+ sw.js verified against workbox)`);
    return;
  }
  for (const [p, text] of Object.entries(want)) {
    if (read(p) !== text) {
      write(p, text);
      console.log('  wrote ' + p);
    }
  }
  const n = await buildSw();
  console.log(`workbox-build: precached ${n} entries -> sw.js`);
  const vendored = copyVendor();
  if (vendored.length) console.log('  vendored ' + vendored.join(', '));
}

if (process.argv[1] && process.argv[1].endsWith('build.mjs')) main();
