// Generates the bilingual search corpus that Pagefind indexes.
//
// Why a corpus at all: the shipped HTML carries English fallback text and the Chinese copy is
// swapped in at runtime from the dictionary, so a static indexer sees zero Chinese characters.
// Measured in round 9: searching the real index returned hits for `hospital`/`WeChat`/`scam`
// and nothing for 挂号/医院/微信/诈骗 — i.e. a search box that is empty for this site's main
// audience. The corpus is built from content/*.json, which already holds both languages plus
// the page each entry belongs to, so no reverse lookup into the dictionary is needed.
//
//   node tools/build-search.mjs            # regenerate _search/**
//   node tools/build-search.mjs check      # drift check, same contract as build.mjs
//   node tools/build-search.mjs index      # corpus + run pagefind
//
// The corpus is deliberately invisible: `robots: noindex`, not in sitemap.xml, not in the
// Lighthouse URL set, not counted as a site page.
//
// zh only. The shipped HTML is already English, so adding English corpus pages produced
// duplicate hits for every English query (measured: 29 English pages indexed for a 14-page
// site). Chinese is the language with no representation on disk, and the language of this
// site's actual audience, so it is the only one a corpus is needed for.

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = '_search';
const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const LANGS = ['zh'];

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function meta(link, anchor) {
  // One field, fragment included. Two comma-separated pairs did not survive Pagefind's
  // data-pagefind-meta parsing: the measured result came back as
  // link = "pages/tutorial-hospital.html,anchor:intro", i.e. the anchor was swallowed.
  return `data-pagefind-meta="link:${link}#${anchor}"`;
}

function page({ lang, title, desc, sections, link, kind }) {
  const body = sections.map((s) => {
    const anchor = meta(link, s.anchor);
    return s.tag === 'h2'
      ? `    <h2 ${anchor}>${esc(s.text)}</h2>`
      : `    <p ${anchor}>${esc(s.text)}</p>`;
  }).join('\n');
  return `<!DOCTYPE html>
<!-- GENERATED by tools/build-search.mjs from content/*.json - edit the JSON, not this file. -->
<html lang="${lang}">
<head>
  <meta charset="UTF-8">
  <meta name="robots" content="noindex">
  <title>${esc(title)}</title>
  <meta name="description" content="${esc(desc || '')}">
</head>
<body>
  <article data-pagefind-kind="${kind}">
    <h1 ${meta(link, 'top')}>${esc(title)}</h1>
${body}
  </article>
</body>
</html>
`;
}

function tutorialDocs(tutorials) {
  const docs = [];
  for (const t of tutorials) {
    if (!t.slug || !t.file) throw new Error(`tutorial missing slug/file: ${JSON.stringify(t).slice(0, 80)}`);
    for (const lang of LANGS) {
      const title = t.h1 && t.h1[lang];
      if (!title) throw new Error(`tutorial ${t.slug} has no h1.${lang} - refusing to emit a half-language corpus`);
      const sections = [];
      if (t.intro && t.intro[lang]) sections.push({ tag: 'p', text: t.intro[lang], anchor: 'intro' });
      for (const [i, step] of (t.steps || []).entries()) {
        const head = step && step[lang] && (step[lang].title || step[lang].t);
        if (head) sections.push({ tag: 'h2', text: head, anchor: `step-${i + 1}` });
        const paras = (step && step[lang] && (step[lang].body || step[lang].p)) || [];
        (Array.isArray(paras) ? paras : [paras]).forEach((p, j) => {
          if (p) sections.push({ tag: 'p', text: p, anchor: `step-${i + 1}${j ? '-' + j : ''}` });
        });
      }
      docs.push({ path: `${OUT}/${lang}/${t.slug}.html`, html: page({ lang, title, desc: t.desc && t.desc[lang], sections, link: `pages/${t.file}`, kind: 'tutorial' }) });
    }
  }
  return docs;
}

function fraudDocs(cases) {
  const docs = [];
  for (const c of cases) {
    if (c.n === undefined) throw new Error(`fraud case missing n: ${JSON.stringify(c).slice(0, 80)}`);
    for (const lang of LANGS) {
      const title = c.title && c.title[lang];
      if (!title) throw new Error(`fraud case ${c.n} has no title.${lang} - refusing half-language corpus`);
      const sections = [];
      const push = (label, text) => { if (text) sections.push({ tag: 'h2', text: `${label} ${text}`, anchor: 'body' }); };
      const say = c.say && c.say[lang];
      const howp = c.howp && c.howp[lang];
      const stop = c.stop && c.stop[lang];
      const warn = c.warn && c.warn[lang];
      push(c.how && c.how[lang], howp);
      push(say && say.label, say && say.text);
      push(c.what && c.what[lang], c.why && c.why[lang]);
      sections.push(...(Array.isArray(stop) ? stop : []).map((s, i) => ({ tag: 'p', text: s, anchor: `stop-${i + 1}` })));
      push('警示', warn);
      docs.push({
        path: `${OUT}/${lang}/fraud-${c.n}.html`,
        html: page({ lang, title, desc: (c.howp && c.howp[lang]) || '', sections, link: 'pages/fraud-database.html', kind: 'fraud' }),
      });
    }
  }
  return docs;
}

function collect() {
  const tutorials = JSON.parse(read('content/tutorials.json')).tutorials;
  const cases = JSON.parse(read('content/fraud-cases.json')).cases;
  return [...tutorialDocs(tutorials), ...fraudDocs(cases)];
}

function writeAll(docs) {
  for (const d of docs) {
    const fp = join(ROOT, d.path);
    mkdirSync(dirname(fp), { recursive: true });
    writeFileSync(fp, d.html, 'utf8');
  }
}

function fingerprint(docs) {
  const h = createHash('sha256');
  for (const d of [...docs].sort((a, b) => a.path.localeCompare(b.path))) {
    h.update(d.path).update('\0').update(d.html).update('\0');
  }
  return h.digest('hex').slice(0, 16);
}

function prune(expected) {
  const want = new Set(expected.map((d) => d.path));
  const removed = [];
  for (const lang of LANGS) {
    const dir = join(ROOT, OUT, lang);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir)) {
      const rel = `${OUT}/${lang}/${f}`;
      if (!want.has(rel)) {
        rmSync(join(ROOT, rel));
        removed.push(rel);
      }
    }
  }
  return removed;
}

function shippedPaths() {
  // The committed staging ledger (reports/deploy-staging.json, written by tools/stage-site.py)
  // is the one place that declares what actually ships. This used to regex the `cp -r` line out
  // of deploy-pages.yml - a fourth consumer of a hand-copied list, and the reason indexing can
  // never drift from deployment. Indexing the working tree instead swept in node_modules HTML and
  // left pagefind reporting a third, `unknown` language for a 14-page site
  // (evidence: wasm.unknown.pagefind in the output).
  const LEDGER = join('reports', 'deploy-staging.json');
  let ledger;
  try {
    ledger = JSON.parse(read(LEDGER));
  } catch (e) {
    throw new Error(`${LEDGER} is missing or unreadable - run: python tools/stage-site.py check --write`);
  }
  const files = (ledger.profiles && ledger.profiles.deploy && ledger.profiles.deploy.committed_files) || [];
  if (files.length < 40) {
    throw new Error(`${LEDGER} lists ${files.length} committed deploy files, expected >= 40 - refusing to index a subset`);
  }
  return files.filter((f) => !f.endsWith('.md'));
}

function stage(dir) {
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  // The corpus is an indexing input, not a deliverable: only the compiled pagefind/ output is
  // shipped, so _search/ is staged here rather than added to the deploy cp list.
  for (const token of [...shippedPaths(), OUT]) {
    const src = join(ROOT, token);
    if (!existsSync(src)) continue;
    cpRecursive(src, join(dir, token));
  }
  return dir;
}

function cpRecursive(src, dest) {
  const st = statSync(src);
  if (st.isDirectory()) {
    mkdirSync(dest, { recursive: true });
    for (const f of readdirSync(src)) {
      if (f === 'node_modules' || f === '.git' || f === '__pycache__' || f === 'pagefind') continue;
      cpRecursive(join(src, f), join(dest, f));
    }
  } else {
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, readFileSync(src));
  }
}

function pagefindInto(bin, siteDir, outSubdir) {
  const r = spawnSync(bin, ['--site', siteDir, '--output-subdir', outSubdir], {
    cwd: siteDir, encoding: 'utf8', shell: process.platform === 'win32',
  });
  if (r.status !== 0) {
    console.error(r.stderr || r.stdout || `pagefind failed for ${outSubdir}`);
    process.exit(1);
  }
  return (r.stdout || '');
}

/**
 * Two single-language indexes, one per UI language.
 *
 * Pagefind 1.5.2's web API on this build exposes no `setLanguage` (instance methods are only
 * init / search / debouncedSearch / filters / mergeIndex / preload / destroy - enumerated in the
 * browser), so a merged multi-language index cannot be switched at runtime. Splitting instead
 * lets the page import `pagefind/<lang>/pagefind.js`, and each half rests on a measurement:
 * a zh-only index answered 挂号 (round 9 scratch test) and the English pages answered
 * hospital/WeChat/scam (round 9, same machine).
 */
function runIndex() {
  const bin = join(ROOT, 'node_modules', '.bin', process.platform === 'win32' ? 'pagefind.cmd' : 'pagefind');
  if (!existsSync(bin)) {
    console.error('pagefind binary missing - run `npm ci` first');
    process.exit(2);
  }
  const base = join(tmpdir(), `fc-idx-${process.pid}`);
  const summary = [];
  try {
    rmSync(join(ROOT, 'pagefind'), { recursive: true, force: true });

    const enStage = join(base, 'en');
    rmSync(enStage, { recursive: true, force: true });
    mkdirSync(enStage, { recursive: true });
    for (const token of shippedPaths()) {
      const src = join(ROOT, token);
      if (existsSync(src)) cpRecursive(src, join(enStage, token));
    }
    pagefindInto(bin, enStage, 'pagefind');
    cpRecursive(join(enStage, 'pagefind'), join(ROOT, 'pagefind', 'en'));
    summary.push(`en:${pageTotal(join(ROOT, 'pagefind', 'en'))}p`);

    const zhStage = join(base, 'zh');
    rmSync(zhStage, { recursive: true, force: true });
    mkdirSync(zhStage, { recursive: true });
    cpRecursive(join(ROOT, OUT), join(zhStage, OUT));
    pagefindInto(bin, zhStage, 'pagefind');
    cpRecursive(join(zhStage, 'pagefind'), join(ROOT, 'pagefind', 'zh'));
    summary.push(`zh:${pageTotal(join(ROOT, 'pagefind', 'zh'))}p`);
  } finally {
    rmSync(base, { recursive: true, force: true });
  }
  return `${summary.join(' ')} | ${Math.round(dirBytes(join(ROOT, 'pagefind')) / 1024)} KiB`;
}

function pageTotal(dir) {
  // Sum page_count across whatever languages this half ended up with; a half that indexed
  // zero pages is a broken build, not an empty result.
  const entry = JSON.parse(readFileSync(join(dir, 'pagefind-entry.json'), 'utf8'));
  return Object.values(entry.languages).reduce((a, v) => a + v.page_count, 0);
}

function dirBytes(dir) {
  let total = 0;
  for (const f of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, f.name);
    total += f.isDirectory() ? dirBytes(p) : statSync(p).size;
  }
  return total;
}
function onDisk() {
  const out = [];
  for (const lang of LANGS) {
    const dir = join(ROOT, OUT, lang);
    if (!existsSync(dir)) continue;
    for (const f of readdirSync(dir)) out.push(`${OUT}/${lang}/${f}`);
  }
  return out;
}

function main() {
  const mode = process.argv[2] || 'build';
  const docs = collect();
  const expected = new Set(docs.map((d) => d.path));

  if (mode === 'check') {
    const problems = [];
    for (const d of docs) {
      const fp = join(ROOT, d.path);
      if (!existsSync(fp)) problems.push(`${d.path} missing`);
      else if (readFileSync(fp, 'utf8') !== d.html) problems.push(`${d.path} differs from content/*.json`);
    }
    for (const p of onDisk()) if (!expected.has(p)) problems.push(`${p} is not produced by content/*.json`);
    if (problems.length) {
      console.error(`build-search drift in ${problems.length} place(s):`);
      for (const p of problems.slice(0, 8)) console.error('  - ' + p);
      return 1;
    }
    console.log(`check: ${docs.length} search corpus files in sync (${fingerprint(docs)})`);
    return 0;
  }
  if (mode === 'clean') {
    rmSync(join(ROOT, OUT), { recursive: true, force: true });
    rmSync(join(ROOT, 'pagefind'), { recursive: true, force: true });
    console.log('removed _search/ and pagefind/');
    return 0;
  }
  writeAll(docs);
  const removed = prune(docs);
  const bytes = docs.reduce((a, d) => a + statSync(join(ROOT, d.path)).size, 0);
  console.log(`built ${docs.length} corpus files (${LANGS.join('/')}), ${Math.round(bytes / 1024)} KiB` +
    (removed.length ? `, pruned ${removed.length} stale` : ''));
  if (mode === 'index') {
    console.log('pagefind:', runIndex() || 'no summary lines');
  }
  return 0;
}

process.exit(main());
