#!/usr/bin/env python3
"""Own the triage table that AGENTS.md used to copy by hand.

Why this exists (round 37, measured before writing a line): `AGENTS.md` promises that the triage
table's authority is `tools/ci-watch.py`'s `HINTS`, and that the document is only the human copy.
That promise was already false. Both sides had nine rows - so any check comparing the two lengths
would have gone green - while three rows existed only in the document and three only in the table:
the document had lost `node half reports no drift`, `HTTP 404` and `precache revision`, and it kept
`本地全绿、CI 红` and `后台任务通知"exit 0"`, which are not log signatures at all and therefore can
never fire. This is the repository's failure class 6 (a list maintained by hand in two places stops
being true), caught in the file that documents the class.

So the table is generated. `HINTS` stays where the prose says it is (ci-watch owns the rows), and
this tool is the only writer of the document section between the markers. CI runs `--check`; a hand
edit between the markers reddens the chain instead of quietly becoming the new truth.

Usage:
  python tools/triage.py --check     # is the document what HINTS says? (CI)
  python tools/triage.py --write     # rewrite the section from HINTS (local, then commit)
  python tools/triage.py --print     # the table alone, for review
  python tools/triage.py --coverage  # how many chain failure shapes the signatures attribute
  python tools/triage.py --selftest  # both directions, offline
Exit: 0 in sync | 1 drift or a row the table cannot render | 2 could not measure
"""
import argparse
import importlib.util
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DOC = os.path.join(ROOT, 'AGENTS.md')
BEGIN = '<!-- BEGIN:TRIAGE-TABLE generated by `python tools/triage.py --write` - do not hand-edit -->'
END = '<!-- END:TRIAGE-TABLE -->'
HEAD = ('| 日志里的原话 | 真实成因 | 处置 |', '|---|---|---|')


def load_watch():
    """ci-watch.py has a hyphen, so it is loaded by path, and it stays the owner of the rows."""
    spec = importlib.util.spec_from_file_location('ciwatch_triage',
                                                 os.path.join(HERE, 'ci-watch.py'))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def cells(row):
    return row['sig'], row['cause'], row['action']


def render(hints):
    """The table body. A cell carrying a pipe would silently become two columns, so it is refused
    by name rather than emitted as a broken row."""
    bad = []
    for row in hints:
        for label, value in zip(('sig', 'cause', 'action'), cells(row)):
            if '|' in value or '\n' in value:
                bad.append('%s: %s' % (row['sig'][:24], label))
    if bad:
        raise ValueError('triage row(s) cannot be rendered as a markdown table (pipe or newline in '
                         'a cell): %s' % ', '.join(bad))
    return list(HEAD) + ['| %s | %s | %s |' % cells(r) for r in hints]


def section(text):
    """(before, body, after) of the marked block, or (None, None, None) when a marker is missing."""
    if BEGIN not in text or END not in text:
        return None, None, None
    before, rest = text.split(BEGIN, 1)
    body, after = rest.split(END, 1)
    return before, body, after


def apply_to(text, hints):
    """Replace the marked block. Missing markers are a named refusal: appending a table somewhere
    would let a document keep two versions of the truth."""
    if not hints:
        raise ValueError('HINTS is empty - refusing to generate an empty table (a rule that '
                         'matches nothing is not a pass)')
    before, body, after = section(text)
    if before is None:
        raise ValueError('markers not found in the document; expected both BEGIN and END so the '
                         'generated region is explicit')
    block = BEGIN + '\n' + '\n'.join(render(hints)) + '\n' + END
    return before + block + after


def _rows(body):
    """Data rows only: the header line and the `|---|` rule are shape, not content."""
    return [ln for ln in body.splitlines()
            if ln.startswith('| ') and ln not in HEAD and not ln.startswith('|---')]


def check_doc(text, hints):
    """(ok, detail). `unknown` shapes return None so a reader never sees a silent pass."""
    if BEGIN not in text or END not in text:
        return None, 'markers missing (the document has no generated region to verify)'
    before, body, _after = section(text)
    want = '\n' + '\n'.join(render(hints)) + '\n'
    if body == want:
        return True, '%d rows, byte-identical to HINTS' % len(_rows(body))
    got, exp = _rows(body), _rows(want)
    lost = [ln.split('|')[1].strip() for ln in exp if ln not in got]
    extra = [ln.split('|')[1].strip() for ln in got if ln not in exp]
    return False, 'hand drift: %d row(s) differ (only in HINTS: %s; only in the document: %s)' % (
        len(set(lost) | set(extra)), '; '.join(lost) or '-', '; '.join(extra) or '-')


CHECK_SITE_RE = re.compile(r'^def (t_\w+)\(', re.M)


def coverage(hints, suite_path=None):
    """How many of the chain's own failure shapes a signature would actually attribute.

    Round 37 measured this before wiring anything: `tools/test_build.py` has 308 `check()` call
    sites, and the nine signatures attribute 9 of them (2.9%). So "every red judge must have a hint"
    is not a gate - it is a demand to write 299 rows nobody has ever needed, and the honest response
    to a 2.9% coverage is to make the number visible, not to green it by deleting the question. The
    floor this repo can enforce is monotone: attribution may not shrink.
    """
    import ast
    suite_path = suite_path or os.path.join(ROOT, 'tools', 'test_build.py')
    tree = ast.parse(io.open(suite_path, encoding='utf-8').read())
    sites = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'check':
            parts = []
            for arg in node.args[:3]:
                for sub in ast.walk(arg):
                    if isinstance(sub, ast.Constant) and isinstance(sub.value, str):
                        parts.append(sub.value)
            sites.append(' '.join(parts))
    if not sites:
        raise ValueError('no check() call sites found in %s - an empty population is not a '
                         'measurement' % suite_path)
    per_row = []
    covered = set()
    for i, row in enumerate(hints):
        hits = {j for j, text in enumerate(sites) if re.search(row['pattern'], text, re.I)}
        per_row.append([row['sig'], len(hits)])
        covered |= hits
    return {'sites': len(sites), 'covered_sites': len(covered), 'uncovered_sites': len(sites) -
            len(covered), 'rows': len(hints),
            'per_row': per_row}


def coverage_line(cov):
    return ('COVERAGE sites=%d covered=%d uncovered=%d rows=%d floor=ok'
            % (cov['sites'], cov['covered_sites'], cov['uncovered_sites'], cov['rows']))


def main(argv=None):
    ap = argparse.ArgumentParser()
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    mode.add_argument('--coverage', action='store_true',
                      help='print how many chain failure shapes the signatures attribute')
    mode.add_argument('--print', dest='print_', action='store_true')
    mode.add_argument('--selftest', action='store_true')
    args = ap.parse_args(argv)
    if args.selftest:
        return selftest()

    try:
        hints = load_watch().HINTS
    except (OSError, AttributeError, Exception) as exc:      # noqa: BLE001 - report, never guess
        print('UNVERIFIED: cannot read the triage rows from ci-watch.py (%s: %s)'
              % (type(exc).__name__, str(exc)[:90]))
        return 2

    if args.coverage:
        try:
            cov = coverage(hints)
        except (ValueError, OSError) as exc:
            print('UNVERIFIED: %s' % exc)
            return 2
        print(coverage_line(cov))
        print(json.dumps(cov['per_row'], ensure_ascii=False))
        return 0

    if args.print_:
        try:
            print('\n'.join(render(hints)))
        except ValueError as exc:
            print('FAIL: %s' % exc)
            return 1
        return 0

    if not os.path.exists(DOC):
        print('UNVERIFIED: %s not found' % DOC)
        return 2
    text = io.open(DOC, encoding='utf-8').read()
    try:
        rendered = apply_to(text, hints)
    except ValueError as exc:
        print('FAIL: %s' % exc)
        return 1

    if args.write:
        io.open(DOC, 'w', encoding='utf-8', newline='\n').write(rendered)
        print('WROTE: AGENTS.md triage region from %d triage rows' % len(hints))
        return 0
    ok, detail = check_doc(text, hints)
    if ok is None:
        print('UNVERIFIED: %s' % detail)
        return 2
    print('%s: %s' % ('OK' if ok else 'DRIFT', detail))
    return 0 if ok else 1


JUDGE_REF = re.compile(r'\b(t_[a-z0-9_]+)\b')


def judge_refs(hints):
    """Judge names the rows cite. Round 36's carry-over asked for exactly this: the signatures are
    hand-written and mention judges by name, so renaming a judge silently points a hint at nothing."""
    out = set()
    for row in hints:
        for field in (row['cause'], row['action']):
            out |= set(JUDGE_REF.findall(field))
    return sorted(out)


def _judge_names(text):
    """Defined judge functions in the suite, read off the syntax tree (a regex over `JUDGES = (...)`
    is how round 28 killed a guard: the same code written a different way returned nothing)."""
    import ast
    tree = ast.parse(text)
    return sorted(n.name for n in ast.walk(tree)
                  if isinstance(n, ast.FunctionDef) and n.name.startswith('t_'))


def selftest():
    watch = load_watch()
    hints = watch.HINTS
    cases = []
    cases.append(('the table is non-empty and every row has all three cells',
                  len(hints) >= 6 and all(cells(r) and all(cells(r)) for r in hints),
                  '%d rows' % len(hints)))
    cases.append(('every signature is a regex that compiles',
                  all(_compiles(r['pattern']) for r in hints), 're.compile over patterns'))
    try:
        cov = coverage(hints)
        cases.append(('the attribution population is measured from real check() sites, never typed',
                      cov['sites'] >= 100 and cov['covered_sites'] >= 1 and
                      cov['covered_sites'] + cov['uncovered_sites'] == cov['sites'],
                      coverage_line(cov)))
    except (ValueError, OSError) as exc:
        cases.append(('the attribution population is measured from real check() sites, never typed',
                      False, 'UNVERIFIED: %s' % exc))
    suite = os.path.join(ROOT, 'tools', 'test_build.py')
    judges = set(_judge_names(io.open(suite, encoding='utf-8').read()))
    refs = judge_refs(hints)
    cases.append(('every judge a row cites actually exists (a renamed judge would silently '
                  'unpoint the hint)', not set(refs) - judges,
                  'cited=%s missing=%s' % (len(refs), sorted(set(refs) - judges))))
    cases.append(('the citation set is not empty (a table that names no judge is not attributed)',
                  len(refs) >= 1, '%s' % refs))
    doc = ('# head\n\nintro prose\n' + BEGIN + '\n' + '\n'.join(render(hints)) + '\n' + END +
           '\n\n## tail\nmore prose\n')
    cases.append(('a document generated by this tool is in sync with itself',
                  check_doc(doc, hints)[0] is True, check_doc(doc, hints)[1]))
    cases.append(('rewriting twice changes nothing (the byte-identical acceptance)',
                  apply_to(apply_to(doc, hints), hints) == doc, 'idempotent'))
    edited = doc.replace(render(hints)[-1], '| something invented | x | y |')
    ok, detail = check_doc(edited, hints)
    cases.append(('a hand edit between the markers is drift, not a new truth',
                  ok is False and 'invented' in detail, detail[:96]))
    dropped = doc.replace(render(hints)[2] + '\n', '')
    cases.append(('a row deleted by hand is named, not counted away',
                  check_doc(dropped, hints)[0] is False
                  and 'only in HINTS' in check_doc(dropped, hints)[1],
                  check_doc(dropped, hints)[1][:96]))
    # The live defect this round measured: both sides had nine rows, three of each were different.
    # A length comparison passes it, so the fixture proves the row-set comparison is what bites.
    swapped = doc
    first = render(hints)[2]
    last = render(hints)[-1]
    swapped = swapped.replace(first, '| ' + first.split('|')[1].strip() + ' A | b | c |')
    swapped = swapped.replace(last, '| ' + last.split('|')[1].strip() + ' B | b | c |')
    cases.append(('same row count with different content is still red (length would pass)',
                  check_doc(swapped, hints)[0] is False
                  and len(_rows(swapped)) == len(_rows(doc)),
                  '%d vs %d rows; %s' % (len(_rows(swapped)), len(_rows(doc)),
                                         check_doc(swapped, hints)[1][:70])))
    cases.append(('missing markers are a named refusal, never a silent append',
                  'markers not found' in str(_err(apply_to, 'no block here', hints)),
                  str(_err(apply_to, 'no block here', hints))[:80]))
    cases.append(('missing markers cannot be checked, so the answer is UNVERIFIED not OK',
                  check_doc('nothing marked', hints)[0] is None, str(check_doc('x', hints)[1])[:60]))
    cases.append(('an empty row set is refused, not rendered as a green empty table',
                  'empty' in str(_err(apply_to, doc, [])), str(_err(apply_to, doc, []))[:80]))
    broken = [dict(hints[0], cause='has | pipe')]
    cases.append(('a cell carrying a pipe is refused (it would silently add a column)',
                  'pipe or newline' in str(_err(render, broken)),
                  str(_err(render, broken))[:80]))
    cases.append(('the ci-watch advice path still fires on the real signature',
                  any('npm ci' in a for a in watch.advice('Error: Cannot find package x')),
                  str(watch.advice('Error: Cannot find package x'))[:60]))
    cases.append(('an unmatched log still produces no advice (the table is not a net that catches '
                  'everything and says so)', not watch.advice('totally unrelated'),
                  str(watch.advice('totally unrelated'))))
    cases.append(('the document itself is in sync right now (this is CI, not a fixture)',
                  check_doc(io.open(DOC, encoding='utf-8').read(), hints)[0] is True,
                  check_doc(io.open(DOC, encoding='utf-8').read(), hints)[1]))
    bad = 0
    for name, passed, detail in cases:
        print('  %s %s (%s)' % ('ok ' if passed else 'SELFTEST-FAIL', name, str(detail)[:110]))
        bad += 0 if passed else 1
    print('triage selftest: %d cases, %d failures' % (len(cases), bad))
    return 1 if bad else 0


def _compiles(pattern):
    try:
        re.compile(pattern)
        return True
    except re.error:
        return False


def _err(fn, *a):
    try:
        return fn(*a)
    except ValueError as exc:
        return exc


if __name__ == '__main__':
    sys.exit(main())
